name = "TextPreprocessing"
uuid = "fb0d870a-c8ad-11e8-1790-ff801a08c705"
authors = ["Maxi Wess <maxwess@googlemail.com>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
